### PR TITLE
Add actions to test and build binaries for x86_64/arm64

### PR DESCRIPTION
**Pull request by apenney**
Hi!

We really need to build this binary for arm64 (we're switching to m1 macs) and I figured it wouldn't be fair to ask you to put any work in so I whipped this up.  This PR:

* Tests on Go 1.16/1.17 in github actions
* Automatically builds linux/darwin x86_64/arm64 binaries whenever you cut a release

I'd love it if you'd merge this and cut a release :)

### CODE REVIEW

**Comment by a8m** [comment]
Thanks a lot for the contribution @apenney. I'm too busy with other OSS projects lately.

**Comment by a8m** [comment]
Action is failing. 

https://github.com/a8m/envsubst/actions/runs/1492199865

**Comment by apenney** [comment]
Weird, I think go.dev was just acting up, https://go.dev/VERSION?m=text was failing - I think another run will magically fix it :(

**Comment by a8m** [comment]
Still failing :|

**Comment by a8m** [comment]
OK, I reverted it for now and uploaded binaries for Linux and Mac (arm64). Please, if you have time to debug and resubmit this PR (maybe check it on your repository), it will be great. Thanks!

**Pull request merged**
